namespace: networkns

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: nginx-deployment
  - path: network-policy-patch.yaml
    target:
      kind: NetworkPolicy
      name: backend-network-policy
