namespace: networkns

# overlays/dev/kustomization.yaml
resources:
  - ../../base

patches:
  - path: backend-network-policy-patch.yaml
    target:
      kind: NetworkPolicy
      name: backend-network-policy
